---
- hosts: webabhi
  become_user: root
  tasks:
  - name: Prequisite of mySql Packages
    shell: name= {{ item }}
    with_items:
     - echo mysql-server-5.1 mysql-server/root_password password root| debconf-set-selections
     - echo mysql-server-5.1 mysql-server/root_password_again password root| debconf-set-selections
 
  - name: Installing MySQL
    apt: 
     name: mysql-server
     update_cache: yes
     state: latest


